# Show colors in console output (and log files)
color-logs: true

# Debug output to console (and log files)
debug-mode: false

# Language file (for translations)
language-file: lang-en.yml

# The amount at which money becomes ingots instead of nuggets
medium-amount: 5.0

# The amount at which money becomes blocks instead of ingots
large-amount: 10.0
