name: "${project.name}"
main: "${project.groupId}.${project.artifactId}.${project.name}"
version: "${project.version}"
description: "${project.name} Purpur Plugin"
author: "BillyGalbreath"
api-version: "1.14"
softdepend:
- Vault
- CraftBook

commands:
    money:
        description: Reload configs
        permission: command.money
        usage: /<command> (reload)

permissions:
    command.money:
        description: Allows reload configs
        default: op
